version: '3.8'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "webapi"
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION_STRING=redis:6379
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
